name: CI

on:
  push:
    branches: [ "main" ]
    tags: 'v*'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: linux
            platform: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - build: macos
            platform: macos-latest
            target: x86_64-apple-darwin

          - build: windows
            platform: windows-latest
            target: x86_64-pc-windows-gnu
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies (linux only)
      if: matrix.build == 'linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Rust cache
      uses: swatinem/rust-cache@v2

    - name: Run Tests
      run: cargo test --locked

    - name: Build
      run: cargo build -r --target ${{ matrix.target }} --locked

    - name: Build Deb
      if: matrix.build == 'linux'
      run: |
        cargo install cargo-deb
        cargo deb -o smart-open.deb

    - name: Rename Binaries (linux / macos)
      if: matrix.build != 'windows'
      run: mv target/${{ matrix.target }}/release/smart-open target/${{ matrix.target }}/release/smart-open-${{ matrix.target }}

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}
        path: |
          target/${{ matrix.target }}/release/smart-open.exe
          target/${{ matrix.target }}/release/smart-open-${{ matrix.target }}
          smart-open.deb

    - name: Upload the binaries
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          target/${{ matrix.target }}/release/smart-open.exe
          target/${{ matrix.target }}/release/smart-open-${{ matrix.target }}
          smart-open.deb
